### ISSUE TITLE
HAT_Test error

### ISSUE THREAD

**Issue by dtchang** [Jpickard1/Hypergraph-Analysis-Toolbox#15]
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 7
      5 import HAT.Hypergraph
      6 import HAT.graph
----> 7 import HAT.plot
      8 import HAT.multilinalg
      9 from itertools import permutations 

ModuleNotFoundError: No module named 'HAT.plot'

**Comment by Jpickard1** [comment]
I'm closing this issue because the testing has been rewritten using `pytest` and a new release is available on PyPI. Apologies for the delay
