### ISSUE TITLE
hello, the picture is so good, how can i draw it? you use HAT draw it?

### ISSUE THREAD

**Issue by 922397935** [Jpickard1/Hypergraph-Analysis-Toolbox#17]
![image](https://github.com/user-attachments/assets/c3bb2fbb-5e6b-4800-99d8-e45aeb7639de)

**Comment by Jpickard1** [comment]
This was actually drawn in latex rather than with HAT. HAT only has visualization for incidence matrices. Here is the corresponding latex code to make this figure can be found here: https://www.overleaf.com/read/qywwkqxtygrn#60b0a2

**Comment by q923397935** [comment]
thank you very much, Good luck
